import * as fs from "fs";
import * as path from "path";
import { ToolResult } from "../types.js";

/**
 * Generates professional boilerplate for a Next.js App Router feature.
 */
function getNextJsBoilerplate(featureName: string, type: "page" | "layout" | "loading" | "error"): string {
  const componentName = featureName.charAt(0).toUpperCase() + featureName.slice(1);
  
  switch (type) {
    case "page":
      return `export default function ${componentName}Page() {\n  return (\n    <div className="container mx-auto p-8">\n      <h1 className="text-3xl font-bold">${componentName}</h1>\n      <p className="mt-4 text-muted-foreground">Generated by LRDEnE WebApp Architect</p>\n    </div>\n  );\n}\n`;
    case "layout":
      return `export default function ${componentName}Layout({ children }: { children: React.ReactNode }) {\n  return <section className="w-full">{children}</section>;\n}\n`;
    case "loading":
      return `export default function Loading() {\n  return <div className="animate-pulse p-8">Loading ${featureName}...</div>;\n}\n`;
    case "error":
      return `'use client';\n\nimport { useEffect } from 'react';\n\nexport default function Error({ error, reset }: { error: Error; reset: () => void }) {\n  useEffect(() => { console.error(error); }, [error]);\n  return (\n    <div className="p-8 text-center">\n      <h2 className="text-destructive">Something went wrong!</h2>\n      <button onClick={() => reset()} className="mt-4 underline">Try again</button>\n    </div>\n  );\n}\n`;
  }
}

export async function scaffold_feature(featureName: string, targetPath: string): Promise<ToolResult<any>> {
  const absPath = path.resolve(targetPath);
  const evidence: string[] = [];

  try {
    // 1. Create directory structure
    if (!fs.existsSync(absPath)) {
      fs.mkdirSync(absPath, { recursive: true });
      evidence.push(`Created directory: ${absPath}`);
    }

    // 2. Generate Boilerplate Files
    const files = [
      { name: "page.tsx", type: "page" },
      { name: "layout.tsx", type: "layout" },
      { name: "loading.tsx", type: "loading" },
      { name: "error.tsx", type: "error" },
    ];

    for (const file of files) {
      const filePath = path.join(absPath, file.name);
      if (!fs.existsSync(filePath)) {
        const content = getNextJsBoilerplate(featureName, file.type as any);
        fs.writeFileSync(filePath, content);
        evidence.push(`Generated: ${file.name}`);
      } else {
        evidence.push(`Skipped: ${file.name} (already exists)`);
      }
    }

    return {
      ok: true,
      summary: `Successfully scaffolded '${featureName}' at ${targetPath}.`,
      data: { featureName, path: targetPath, filesGenerated: files.length },
      evidence
    };
  } catch (error: any) {
    return {
      ok: false,
      summary: `Scaffolding failed: ${error.message}`,
      warnings: [error.message]
    };
  }
}
